### ISSUE TITLE
Potential bugs in autopet/datacentric/dataset.py

### ISSUE THREAD

**Issue by john-lennon-chan** [ClinicalDataScience/datacentric-challenge#3]
Dear Organizer,

When I am running dataset.py's `__main__` to access a sample of the dataset, I received a `FileNotFoundError` in the `__getitem__` method of the `RandomPatientDataset` class. After further investigation, I found that the `__getitem__` method joins the `data_dir`: "../../test/preprocessed" and the `filename`: f"{patient_id}_{random_number:03d}.npz" to form the `filepath`. However, the problem is that the f"{patient_id}_{random_number:03d}.npz" is under the /train or the /val folder which is in the `data_dir`: "../../test/preprocessed". And so I would like to ask the organizer for clarifications on how to address this issue. Thank you very much!

Yours sincerely,
Lennon

**Comment by maxshatskiy** [comment]
I am not organizer, but from what I understood from their code.
In this file (https://github.com/ClinicalDataScience/datacentric-challenge/blob/main/scripts/preprocess_augmentations.py)
they create preprocesses (samples/transformed) dataset from original data. Their idea is to preprocess dataset so that training runs faster afterwards. You have to run this first this will create files in /test/preprocessed.
In the dataloader (https://github.com/ClinicalDataScience/datacentric-challenge/blob/main/autopet3/datacentric/dataloader.py)
based on the if suffix == ".npz" it will use this "preprocessed dataset", otherwise if you use .npz.gz it will use original data and will do transformation on the fly.
You do not have to do preprocessing as they do this if you ready to wait longer training or have big computational resources, or your transformations are simple to be executed fast.

**Comment by BalthasarSchachtner** [comment]
Dear Lennon,
sorry for the delayed answer, I think I found the issue and fixed it here: https://github.com/ClinicalDataScience/datacentric-challenge/commit/c437258c292fd0bd3f6274f54ddb0d602612b1b7
Best,
Balthasar

**Comment by john-lennon-chan** [comment]
> I am not organizer, but from what I understood from their code. In this file (https://github.com/ClinicalDataScience/datacentric-challenge/blob/main/scripts/preprocess_augmentations.py) they create preprocesses (samples/transformed) dataset from original data. Their idea is to preprocess dataset so that training runs faster afterwards. You have to run this first this will create files in /test/preprocessed. In the dataloader (https://github.com/ClinicalDataScience/datacentric-challenge/blob/main/autopet3/datacentric/dataloader.py) based on the if suffix == ".npz" it will use this "preprocessed dataset", otherwise if you use .npz.gz it will use original data and will do transformation on the fly. You do not have to do preprocessing as they do this if you ready to wait longer training or have big computational resources, or your transformations are simple to be executed fast.


Thank you very much for the suggestion, the transformations on the fly are really taking a lot time.

**Comment by john-lennon-chan** [comment]
> Dear Lennon, sorry for the delayed answer, I think I found the issue and fixed it here: [c437258](https://github.com/ClinicalDataScience/datacentric-challenge/commit/c437258c292fd0bd3f6274f54ddb0d602612b1b7) Best, Balthasar

And thank you for the fix.
